### PR TITLE
Add 'resolve' to refer-clojure  clause in core.cljs

### PR DESCRIPTION
**Pull request by zachcurry**
Added exclusion to fix the following compiler warning:

----  Compiler Warning on   <path>/jayq/core.cljs   line:529  column:1  ----

  resolve already refers to: cljs.core/resolve being replaced by: jayq.core/resolve

  525  (defn notify-with
  526    [deferred context args]
  527    (.notifyWith deferred context args))
  528  
  529  (defn resolve
       ^--- resolve already refers to: cljs.core/resolve being replaced by: jayq.core/resolve
  530    [deferred args]
  531    (.resolve deferred args))
  532  
  533  (defn resolve-with
  534    [deferred context args]

----  Compiler Warning : Please see <path>/jayq/core.cljs  ----

### CODE REVIEW

**Comment by zachcurry** [comment]
RIP

**Comment by zachcurry** [comment]
:pours 40oz onto ground:

Would you be interested in maintaining a fork of this thing with me? Seems like it would be pretty low maintenance 🤔

**Comment by ibdknox** [comment]
I added both of you as collaborators :) Let me know if you need anything else.

**Comment by zachcurry** [comment]
:slurps 40oz off ground:

Thanks, @ibdknox !

**Pull request closed without merging**
